name: tium
description: "Plant Companion & Daily Green"
publish_to: 'none'
version: 1.0.11+14

environment:
  sdk: ^3.8.0-231.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # db
  shared_preferences: ^2.5.3
  hive_flutter: ^1.1.0

  # firebase
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7

  # web
  flutter_inappwebview: ^6.1.5

  # state management
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3

  # server (backend)
  supabase_flutter: ^2.9.1

  # db
  hive_generator: ^2.0.1

  # network
  dio: ^5.8.0+1
  xml: ^6.5.0

  # share
  share_plus: ^11.0.0
  url_launcher: ^6.3.1

  # launch Icon
  flutter_launcher_icons: ^0.14.4

  # Cached
  cached_network_image: ^3.4.1

  # notification
  flutter_local_notifications: ^19.4.0
  firebase_messaging: ^15.2.5

  # permission
  permission_handler: ^12.0.0+1

  # Location
  geolocator: ^14.0.1

  # version management
  package_info_plus: ^8.3.0

  # conversion
  xml2json: ^6.2.7

  # etc (UI)
  equatable: ^2.0.7
  smooth_page_indicator: ^1.2.1
  loading_animation_widget: ^1.3.0
  lottie: ^3.3.1
  intl: ^0.20.2
  carousel_slider: ^5.1.1
  shimmer_animation: ^2.2.2
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1
  image_picker: ^1.1.2
  fluttertoast: ^8.2.12
  path_provider: ^2.1.5
  path: ^1.9.1
  uuid: ^4.5.1
  image_picker_ios: ^0.8.12+2
  flutter_image_compress: ^2.4.0
  flutter_native_splash: ^2.4.6
  android_notification_icons: ^0.0.1
  device_info_plus: ^11.5.0
  day_night_time_picker: ^1.3.1
  flutter_dotenv: ^5.2.1
  json_annotation: ^4.9.0
  auto_size_text: ^3.0.0

android_notification_icons:
  image_path: 'assets/icon/ic_notification.png'
  icon_name: 'ic_notification' # optional

flutter_native_splash:
  android: true
  ios: true
  web: true
  image: "assets/icon/icon.png"
  image_dark: "assets/icon/icon.png"
  background_image: "assets/icon/background.png"
  background_image_dark: "assets/icon/background.png"
  android_12:
    color: "#263238"
    color_dark: "#263238"
    image: "assets/icon/splash_android.png"
    image_dark: "assets/icon/splash_android.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  flutter_oss_licenses: ^3.0.4
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/img/
    - assets/icon/
    - assets/avatar/
    - .env

