name: grodi
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.0-231.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # db
  shared_preferences: ^2.5.3
  hive_flutter: ^1.1.0

  # firebase
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7

  # web
  flutter_inappwebview: ^6.1.5

  # state management
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3

  # notification
  flutter_local_notifications: ^19.1.0
  firebase_messaging: ^15.2.5

  # permission
  permission_handler: ^12.0.0+1

  # version management
  package_info_plus: ^8.3.0

  # etc
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
